from django.db import models
from django.contrib.auth.models import AbstractUser

from utils.jwt_utils import User

class Order(models.Model):
    class Meta:
        db_table = 'tb_order'

    key = models.CharField("订单编号", max_length=255, null=True)
    buyer = models.CharField("买家会员名", max_length=255, null=True)
    buyer_alipay = models.CharField("买家支付宝账号", max_length=255, null=True)
    pay_detail = models.CharField("支付详情", max_length=255, null=True)
    buyer_pay = models.FloatField("买家应付货款", default=0)
    buyer_postage = models.FloatField("买家应付邮费", default=0)
    buyer_bonus = models.FloatField("买家支付积分", default=0)
    total_amount = models.FloatField("总金额", default=0)
    return_bonus = models.FloatField("返点积分", default=0)
    buyer_real_pay = models.FloatField("买家实际支付金额", default=0)
    buyer_real_bonus = models.FloatField("买家实际支付积分", default=0)
    # consumer = models.FloatField("买家实际支付积分", max_length=255, null=True)
    # consumer = models.FloatField("买家实际支付积分", max_length=255, null=True)

    order_status = models.CharField("订单状态", max_length=255, null=True)
    buyer_comment = models.CharField("买家留言", max_length=255, null=True)
    receiver_name = models.CharField("收货人姓名", max_length=255, null=True)
    receiver_addr = models.CharField("收货地址 ", max_length=255, null=True)
    ship_way = models.CharField("运送方式", max_length=255, null=True)
    tel = models.CharField("联系电话 ", max_length=255, null=True)
    phone = models.CharField("联系手机", max_length=255, null=True)
    order_create_at = models.DateTimeField("订单创建时间", auto_now_add=True)
    order_pay_at = models.DateTimeField("订单付款时间", auto_now=True)
    title = models.CharField("宝贝标题 ", max_length=255, null=True)
    category = models.IntegerField("宝贝种类")
    ship_number = models.CharField("物流单号", max_length=255, null=True)
    ship_company = models.CharField("物流公司 ", max_length=255, null=True)
    order_remark = models.CharField("订单备注 ", max_length=255, null=True)
    total_count = models.IntegerField("宝贝总数量 ")
    shop_id = models.IntegerField("店铺Id ")
    shop_name = models.CharField("店铺名称 ", max_length=255, null=True)
    order_close_reason = models.CharField("订单关闭原因 ", max_length=255, null=True)
    seller_fee = models.FloatField("卖家服务费", default=0)
    buyer_fee = models.FloatField("买家服务费", default=0)
    invoice = models.CharField("发票抬头 ", max_length=255, null=True)
    is_phone_order = models.CharField("是否手机订单 ", max_length=255, null=True)
    stage_order_info = models.CharField("分阶段订单信息 ", max_length=255, null=True)
    pro_order_id = models.CharField("特权订金订单id ", max_length=255, null=True)

    is_contract_photo = models.BooleanField("是否上传合同照片", default=False)
    is_receipt = models.BooleanField("是否上传小票", default=False)
    is_pay_by_other = models.BooleanField("是否代付", default=False)

    edit_sku = models.CharField("修改后的sku ", max_length=255, null=True)
    edit_addr = models.CharField("修改后的收货地址 ", max_length=255, null=True)
    exception_info = models.CharField("异常信息 ", max_length=255, null=True)
    tmall_coupons = models.FloatField("天猫卡券抵扣 ", default=0)
    jifen_coupons = models.FloatField("集分宝抵扣 ", default=0)
    is_o2o = models.BooleanField("是否是O2O交易 ", default=False)
    new_retail_type = models.CharField("新零售交易类型 ", max_length=255, null=True)
    new_retail_shop_name = models.CharField("新零售导购门店名称 ", max_length=255, null=True)
    new_retail_shop_id = models.CharField("新零售导购门店id ", max_length=255, null=True)
    new_retail_send_shop_name = models.CharField("新零售发货门店名称 ", max_length=255, null=True)
    new_retail_send_shop_id = models.CharField("新零售发货门店id ", max_length=255, null=True)
    refund_amount = models.FloatField("退款金额 ", default=0)
    reserve_shop = models.CharField("预约门店 ", max_length=255, null=True)
    is_village_order = models.BooleanField("是否村淘订单 ", default=False)
    confirm_receipt_time = models.DateTimeField("确认收货时间 ", auto_now_add=True)
    seller_money = models.FloatField("打款商家金额 ", default=0)
    person_money = models.FloatField("含应开票给个人的个人红包 ", default=0)
    is_credit_buy = models.BooleanField("是否信用购 ", default=False)
    experience_end_time = models.DateTimeField("体验期结束时间 ", auto_now_add=True)
    gift = models.CharField("前N有礼 ", max_length=255, null=True)
    delivery_type = models.CharField("配送类型 ", max_length=255, null=True)
    live_cash_status = models.CharField("直播返现状态 ", max_length=255, null=True)
    cash_amount = models.FloatField("返现金额 ", default=0)
    delay_send_amount = models.FloatField("延迟发货自动赔付金额 ", default=0)
    new_retail_deal_shop_name = models.CharField("新零售成交门店昵称 ", max_length=255, null=True)
    new_retail_deal_shop_id = models.CharField("新零售成交门店id ", max_length=255, null=True)
    new_retail_dealer_id = models.CharField("新零售成交经销商id  ", max_length=255, null=True)
    main_order_key = models.CharField("主订单编号 ", max_length=255, null=True)

    valid = models.BooleanField("是否有效 ", default=True)