# Generated by Django 2.2.13 on 2020-11-23 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, null=True, verbose_name='订单编号')),
                ('buyer', models.CharField(max_length=255, null=True, verbose_name='买家会员名')),
                ('buyer_alipay', models.CharField(max_length=255, null=True, verbose_name='买家支付宝账号')),
                ('pay_detail', models.CharField(max_length=255, null=True, verbose_name='支付详情')),
                ('buyer_pay', models.FloatField(default=0, verbose_name='买家应付货款')),
                ('buyer_postage', models.FloatField(default=0, verbose_name='买家应付邮费')),
                ('buyer_bonus', models.FloatField(default=0, verbose_name='买家支付积分')),
                ('total_amount', models.FloatField(default=0, verbose_name='总金额')),
                ('return_bonus', models.FloatField(default=0, verbose_name='返点积分')),
                ('buyer_real_pay', models.FloatField(default=0, verbose_name='买家实际支付金额')),
                ('buyer_real_bonus', models.FloatField(default=0, verbose_name='买家实际支付积分')),
                ('order_status', models.CharField(max_length=255, null=True, verbose_name='订单状态')),
                ('buyer_comment', models.CharField(max_length=255, null=True, verbose_name='买家留言')),
                ('receiver_name', models.CharField(max_length=255, null=True, verbose_name='收货人姓名')),
                ('receiver_addr', models.CharField(max_length=255, null=True, verbose_name='收货地址 ')),
                ('ship_way', models.CharField(max_length=255, null=True, verbose_name='运送方式')),
                ('tel', models.CharField(max_length=255, null=True, verbose_name='联系电话 ')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='联系手机')),
                ('order_create_at', models.DateTimeField(auto_now_add=True, verbose_name='订单创建时间')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='宝贝标题 ')),
                ('category', models.IntegerField(verbose_name='宝贝种类')),
                ('ship_number', models.CharField(max_length=255, null=True, verbose_name='物流单号')),
                ('ship_company', models.CharField(max_length=255, null=True, verbose_name='物流公司 ')),
                ('order_remark', models.CharField(max_length=255, null=True, verbose_name='订单备注 ')),
                ('total_count', models.IntegerField(verbose_name='宝贝总数量 ')),
                ('shop_id', models.IntegerField(verbose_name='店铺Id ')),
                ('shop_name', models.CharField(max_length=255, null=True, verbose_name='店铺名称 ')),
                ('order_close_reason', models.CharField(max_length=255, null=True, verbose_name='订单关闭原因 ')),
                ('seller_fee', models.FloatField(default=0, verbose_name='卖家服务费')),
                ('buyer_fee', models.FloatField(default=0, verbose_name='买家服务费')),
                ('invoice', models.CharField(max_length=255, null=True, verbose_name='发票抬头 ')),
                ('is_phone_order', models.CharField(max_length=255, null=True, verbose_name='是否手机订单 ')),
                ('stage_order_info', models.CharField(max_length=255, null=True, verbose_name='分阶段订单信息 ')),
                ('pro_order_id', models.CharField(max_length=255, null=True, verbose_name='特权订金订单id ')),
                ('is_contract_photo', models.BooleanField(default=False, verbose_name='是否上传合同照片')),
                ('is_receipt', models.BooleanField(default=False, verbose_name='是否上传小票')),
                ('is_pay_by_other', models.BooleanField(default=False, verbose_name='是否代付')),
                ('edit_sku', models.CharField(max_length=255, null=True, verbose_name='修改后的sku ')),
                ('edit_addr', models.CharField(max_length=255, null=True, verbose_name='修改后的收货地址 ')),
                ('exception_info', models.CharField(max_length=255, null=True, verbose_name='异常信息 ')),
                ('tmall_coupons', models.FloatField(default=0, verbose_name='天猫卡券抵扣 ')),
                ('jifen_coupons', models.FloatField(default=0, verbose_name='集分宝抵扣 ')),
                ('is_o2o', models.BooleanField(default=False, verbose_name='是否是O2O交易 ')),
                ('new_retail_type', models.CharField(max_length=255, null=True, verbose_name='新零售交易类型 ')),
                ('new_retail_shop_name', models.CharField(max_length=255, null=True, verbose_name='新零售导购门店名称 ')),
                ('new_retail_shop_id', models.CharField(max_length=255, null=True, verbose_name='新零售导购门店id ')),
                ('new_retail_send_shop_name', models.CharField(max_length=255, null=True, verbose_name='新零售发货门店名称 ')),
                ('new_retail_send_shop_id', models.CharField(max_length=255, null=True, verbose_name='新零售发货门店id ')),
                ('refund_amount', models.FloatField(default=0, verbose_name='退款金额 ')),
                ('reserve_shop', models.CharField(max_length=255, null=True, verbose_name='预约门店 ')),
                ('is_village_order', models.BooleanField(default=False, verbose_name='是否村淘订单 ')),
                ('confirm_receipt_time', models.DateTimeField(auto_now_add=True, verbose_name='确认收货时间 ')),
                ('seller_money', models.FloatField(default=0, verbose_name='打款商家金额 ')),
                ('person_money', models.FloatField(default=0, verbose_name='含应开票给个人的个人红包 ')),
                ('is_credit_buy', models.BooleanField(default=False, verbose_name='是否信用购 ')),
                ('experience_end_time', models.DateTimeField(auto_now_add=True, verbose_name='体验期结束时间 ')),
                ('gift', models.CharField(max_length=255, null=True, verbose_name='前N有礼 ')),
                ('delivery_type', models.CharField(max_length=255, null=True, verbose_name='配送类型 ')),
                ('live_cash_status', models.CharField(max_length=255, null=True, verbose_name='直播返现状态 ')),
                ('cash_amount', models.FloatField(default=0, verbose_name='返现金额 ')),
                ('delay_send_amount', models.FloatField(default=0, verbose_name='延迟发货自动赔付金额 ')),
                ('new_retail_deal_shop_name', models.CharField(max_length=255, null=True, verbose_name='新零售成交门店昵称 ')),
                ('new_retail_deal_shop_id', models.CharField(max_length=255, null=True, verbose_name='新零售成交门店id ')),
                ('new_retail_dealer_id', models.CharField(max_length=255, null=True, verbose_name='新零售成交经销商id  ')),
                ('main_order_key', models.CharField(max_length=255, null=True, verbose_name='主订单编号 ')),
            ],
            options={
                'db_table': 'tb_order',
            },
        ),
    ]
