# Generated by Django 2.2.13 on 2020-11-26 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_time',
            field=models.DateTimeField(auto_now=True, verbose_name='付款时间 '),
        ),
    ]
