# Generated by Django 2.2.13 on 2020-11-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20201126_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='valid',
            field=models.BooleanField(default=True, verbose_name='是否有效 '),
        ),
    ]
